/************************************************************************************
Descripción: Objeto encargado de borrar las secuencias
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_CASOS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_PAGOS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_USUARIOS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_LOCALES;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_EMPRESAS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_CIUDADES_LOCALES;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_ROLES_USUARIOS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_TIPOS_PAGOS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_ESTADOS_PAGOS;
DROP SEQUENCE APP_GEST_LOCALES.SEQ_MBC_ESTADOS_CASOS;
DROP SEQUENCE APP_GEST_LOCALES_CLIENTE.SEQ_MBC_LOGS;