/************************************************************************************
Descripción: Objeto encargado de borrar las tablas
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

DROP TABLE APP_GEST_LOCALES.MBC_CASOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_PAGOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_USUARIOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_LOCALES CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_EMPRESAS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_CIUDADES_LOCALES CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_ROLES_USUARIOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_TIPOS_PAGOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_ESTADOS_PAGOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES.MBC_ESTADOS_CASOS CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES_CLIENTE.MBC_INFORME CASCADE CONSTRAINTS PURGE;
DROP TABLE APP_GEST_LOCALES_CLIENTE.MBC_LOGS CASCADE CONSTRAINTS PURGE;