/************************************************************************************
Descripción: Objeto encargado de crear la tabla "MBC_CASOS"
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

CREATE TABLE APP_GEST_LOCALES.MBC_CASOS
(
	ID_CASO					NUMBER(15),
	DESCRIPCION				VARCHAR2(280)	NOT NULL,
	SOPORTE           		VARCHAR2(260),
	ID_USUARIO				NUMBER(15)		NOT NULL,
	ID_ESTADO_CASO			NUMBER(2)		NOT NULL,
	ID_PAGO					NUMBER(15)		NOT NULL,
	CONSTRAINT MBC_CASOS_UNIQUE UNIQUE (ID_PAGO)
)
TABLESPACE TS_APP_GEST_LOCALES;

COMMENT ON TABLE APP_GEST_LOCALES.MBC_CASOS IS 'CASOS';

COMMENT ON COLUMN APP_GEST_LOCALES.MBC_CASOS.ID_CASO IS 'LLAVE PRIMARIA';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_CASOS.DESCRIPCION IS 'DESCRIPCIÓN DEL CASO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_CASOS.SOPORTE IS 'SOPORTE DEL CASO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_CASOS.ID_USUARIO IS 'USUARIO DEL CASO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_CASOS.ID_ESTADO_CASO IS 'ESTADO DEL CASO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_CASOS.ID_PAGO IS 'PAGO DEL CASO';