/************************************************************************************
Descripción: Objeto encargado de crear la tabla "MBC_LOGS"
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

CREATE TABLE APP_GEST_LOCALES_CLIENTE.MBC_LOGS
(
	ID_LOG				    NUMBER(15),
	LIMITE_INFERIOR         NUMBER(15)	    NOT NULL,
	LIMITE_SUPERIOR         NUMBER(15)	    NOT NULL,
	AÑO					    NUMBER(4)	    NOT NULL,
	ESTADO					VARCHAR2(10)    NOT NULL
)
TABLESPACE TS_APP_GEST_LOCALES_CLIENTE;

COMMENT ON TABLE APP_GEST_LOCALES_CLIENTE.MBC_LOGS IS 'LOGS';

COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_LOGS.ID_LOG IS 'LLAVE PRIMARIA';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_LOGS.LIMITE_INFERIOR IS 'LÍMITE INFERIOR';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_LOGS.LIMITE_SUPERIOR IS 'LÍMITE SUPERIOR';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_LOGS.AÑO IS 'AÑO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_LOGS.ESTADO IS 'ESTADO';