/************************************************************************************
Descripción: Objeto encargado de crear la tabla "MBC_EMPRESAS"
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

CREATE TABLE APP_GEST_LOCALES.MBC_EMPRESAS
(
	ID_EMPRESA			NUMBER(15),
	NOMBRE              VARCHAR2(100)	NOT NULL,
	DOCUMENTO           VARCHAR2(15)	NOT NULL,
	TELEFONO			VARCHAR2(20),
	CONSTRAINT MBC_EMPRESAS_UNIQUE UNIQUE (NOMBRE, DOCUMENTO)
)
TABLESPACE TS_APP_GEST_LOCALES;

COMMENT ON TABLE APP_GEST_LOCALES.MBC_EMPRESAS IS 'EMPRESAS';

COMMENT ON COLUMN APP_GEST_LOCALES.MBC_EMPRESAS.ID_EMPRESA IS 'LLAVE PRIMARIA';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_EMPRESAS.NOMBRE IS 'NOMBRE DE LA EMPRESA';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_EMPRESAS.DOCUMENTO IS 'DOCUMENTO DE LA EMPRESA';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_EMPRESAS.TELEFONO IS 'TELÉFONO DE LA EMPRESA';