/************************************************************************************
Descripción: Objeto encargado de crear la tabla "MBC_USUARIOS"
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

CREATE TABLE APP_GEST_LOCALES.MBC_USUARIOS
(
	ID_USUARIO				NUMBER(15),
	NOMBRE              	VARCHAR2(50)	NOT NULL,
	APELLIDO           		VARCHAR2(50)	NOT NULL,
	CORREO					VARCHAR2(50)	NOT NULL,
	CLAVE					VARCHAR2(32)	NOT NULL,
	TELEFONO				VARCHAR2(20),
	ID_ROL_USUARIO			NUMBER(2)		NOT NULL,
	ID_EMPRESA				NUMBER(15),
	CONSTRAINT MBC_USUARIOS_UNIQUE UNIQUE (CORREO)
)
TABLESPACE TS_APP_GEST_LOCALES;

COMMENT ON TABLE APP_GEST_LOCALES.MBC_USUARIOS IS 'USUARIOS';

COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.ID_USUARIO IS 'LLAVE PRIMARIA';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.NOMBRE IS 'NOMBRE DEL USUARIO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.APELLIDO IS 'APELLIDO DEL USUARIO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.CORREO IS 'CORREO DEL USUARIO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.CLAVE IS 'CLAVE DEL USUARIO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.TELEFONO IS 'TELÉFONO DEL USUARIO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.ID_ROL_USUARIO IS 'ROL DEL USUARIO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_USUARIOS.ID_EMPRESA IS 'EMPRESA DEL USUARIO';