/************************************************************************************
Descripción: Objeto encargado de crear la tabla "MBC_PAGOS"
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

CREATE TABLE APP_GEST_LOCALES.MBC_PAGOS
(
	ID_PAGO						NUMBER(15),
	DESCRIPCION					VARCHAR2(50)	NOT NULL,
	PRECIO           			NUMBER(12, 2)	NOT NULL,
	FECHA_VENCIMIENTO			DATE			NOT NULL,
	SOPORTE						VARCHAR2(260),
	VALOR_PAGADO				NUMBER(12, 2),
	FECHA_PAGO					DATE,
	ID_TIPO_PAGO				NUMBER(2)		NOT NULL,
	ID_ESTADO_PAGO				NUMBER(2)		NOT NULL,
	ID_LOCAL					NUMBER(15)		NOT NULL,
	ID_EMPRESA					NUMBER(15),
	ID_USUARIO					NUMBER(15)
)
TABLESPACE TS_APP_GEST_LOCALES;

COMMENT ON TABLE APP_GEST_LOCALES.MBC_PAGOS IS 'PAGOS';

COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.ID_PAGO IS 'LLAVE PRIMARIA';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.DESCRIPCION IS 'DESCRIPCIÓN DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.PRECIO IS 'PRECIO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.FECHA_VENCIMIENTO IS 'FECHA DE VENCIMIENTO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.SOPORTE IS 'SOPORTE DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.VALOR_PAGADO IS 'VALOR PAGADO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.FECHA_PAGO IS 'FECHA DE PAGO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.ID_TIPO_PAGO IS 'TIPO DE PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.ID_ESTADO_PAGO IS 'ESTADO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.ID_LOCAL IS 'LOCAL DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.ID_EMPRESA IS 'EMPRESA DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES.MBC_PAGOS.ID_USUARIO IS 'USUARIO DEL PAGO';