/************************************************************************************
Descripción: Objeto encargado de crear la tabla "MBC_INFORME"
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

CREATE TABLE APP_GEST_LOCALES_CLIENTE.MBC_INFORME(
    ID_PAGO						NUMBER(15),
    DESCRIPCION					VARCHAR2(50),
    PRECIO           			NUMBER(12, 2),
    FECHA_VENCIMIENTO			DATE,
    SOPORTE						VARCHAR2(260),
    VALOR_PAGADO				NUMBER(12, 2),
    FECHA_PAGO					DATE,
    TIPO_PAGO				    VARCHAR2(10),
    LOCAL                       VARCHAR2(50),
    EMPRESA					    VARCHAR2(100),
    USUARIO					    VARCHAR2(50)
)
TABLESPACE TS_APP_GEST_LOCALES_CLIENTE;

COMMENT ON TABLE APP_GEST_LOCALES_CLIENTE.MBC_INFORME IS 'INFORME';

COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.ID_PAGO IS 'LLAVE PRIMARIA';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.DESCRIPCION IS 'DESCRIPCIÓN DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.PRECIO IS 'PRECIO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.FECHA_VENCIMIENTO IS 'FECHA DE VENCIMIENTO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.SOPORTE IS 'SOPORTE DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.VALOR_PAGADO IS 'VALOR PAGADO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.FECHA_PAGO IS 'FECHA DE PAGO DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.TIPO_PAGO IS 'TIPO DE PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.LOCAL IS 'LOCAL DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.EMPRESA IS 'EMPRESA DEL PAGO';
COMMENT ON COLUMN APP_GEST_LOCALES_CLIENTE.MBC_INFORME.USUARIO IS 'USUARIO DEL PAGO';