/************************************************************************************
Descripción: Objeto encargado de insertar los datos iniciales en las tablas
Autor:       Marlon Pérez Ríos
Fecha:       13-12-2022
IdGestión:   
@copyright:  TechCamp
************************************************************************************/

BEGIN

	-- Insertar datos a la tabla "MBC_TIPOS_PAGOS"
	INSERT INTO APP_GEST_LOCALES.MBC_TIPOS_PAGOS (ID_TIPO_PAGO, TIPO) VALUES (SEQ_MBC_TIPOS_PAGOS.NEXTVAL, 'Arriendo');
	INSERT INTO APP_GEST_LOCALES.MBC_TIPOS_PAGOS (ID_TIPO_PAGO, TIPO) VALUES (SEQ_MBC_TIPOS_PAGOS.NEXTVAL, 'Admon');
	INSERT INTO APP_GEST_LOCALES.MBC_TIPOS_PAGOS (ID_TIPO_PAGO, TIPO) VALUES (SEQ_MBC_TIPOS_PAGOS.NEXTVAL, 'Extra');
	
	-- Insertar datos a la tabla "MBC_ESTADOS_PAGOS"
	INSERT INTO APP_GEST_LOCALES.MBC_ESTADOS_PAGOS (ID_ESTADO_PAGO, ESTADO) VALUES (SEQ_MBC_ESTADOS_PAGOS.NEXTVAL, 'Pendiente');
	INSERT INTO APP_GEST_LOCALES.MBC_ESTADOS_PAGOS (ID_ESTADO_PAGO, ESTADO) VALUES (SEQ_MBC_ESTADOS_PAGOS.NEXTVAL, 'Revisión');
	INSERT INTO APP_GEST_LOCALES.MBC_ESTADOS_PAGOS (ID_ESTADO_PAGO, ESTADO) VALUES (SEQ_MBC_ESTADOS_PAGOS.NEXTVAL, 'Pagado');
	
	-- Insertar datos a la tabla "MBC_ESTADOS_CASOS"
	INSERT INTO APP_GEST_LOCALES.MBC_ESTADOS_CASOS (ID_ESTADO_CASO, ESTADO) VALUES (SEQ_MBC_ESTADOS_CASOS.NEXTVAL, 'Pendiente');
	INSERT INTO APP_GEST_LOCALES.MBC_ESTADOS_CASOS (ID_ESTADO_CASO, ESTADO) VALUES (SEQ_MBC_ESTADOS_CASOS.NEXTVAL, 'Finalizado');
	
	-- Insertar datos a la tabla "MBC_ROLES_USUARIOS"
	INSERT INTO APP_GEST_LOCALES.MBC_ROLES_USUARIOS (ID_ROL_USUARIO, ROL) VALUES (SEQ_MBC_ROLES_USUARIOS.NEXTVAL, 'Admin');
	INSERT INTO APP_GEST_LOCALES.MBC_ROLES_USUARIOS (ID_ROL_USUARIO, ROL) VALUES (SEQ_MBC_ROLES_USUARIOS.NEXTVAL, 'Cliente');
	
	-- Insertar datos a la tabla "MBC_CIUDADES_LOCALES"
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Bogotá');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Medellín');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Cali');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Barranquilla');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Cartagena');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Soacha');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Cúcuta');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Soledad');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Bucaramanga');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Bello');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Villavicencio');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Santa Marta');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Valledupar');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Ibagué');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Montería');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Pereira');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Manizales');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Pasto');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Neiva');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Palmira');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Popayán');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Buenaventura');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Floridablanca');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Armenia');
	INSERT INTO APP_GEST_LOCALES.MBC_CIUDADES_LOCALES (ID_CIUDAD_LOCAL, CIUDAD) VALUES (SEQ_MBC_CIUDADES_LOCALES.NEXTVAL, 'Sincelejo');
	
	-- Insertar datos a la tabla "MBC_EMPRESAS"
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'SEGUROS COMERCIALES BOLIVAR S.A.', '2169462309', '677-565-3557');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Solla S A', '7413888599', '520-952-2158');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Faismon S.A.S.', '8439819153', '166-299-3658');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Industria de Alimentos Zenú SAS', '4643444347', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Contegral S.A.', '5056153648', '321-955-6489');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'ECOPETROL S.A', '5505810330', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'ORGANIZACIÓN TERPEL S.A.', '1517402832', '390-589-5475');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'REFINERIA DE CARTAGENA S.A.S.', '2919158848', '844-766-9078');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'ALMACENES EXITO S A', '6225754393', '442-697-6252');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'EMPRESAS PÚBLICAS DE MEDELLÍN ESP', '2334421596', '401-347-5585');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'AEROVIAS DEL CONTINENTE AMERICANO S.A. - AVIANCA S.A.', '8609474860', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'COMUNICACIÓN CELULAR S.A.', '9793427000', '211-219-2531');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'NUEVA EPS S.A.', '1303963140', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Cenit Transporte y Logística de Hidrocarburos S.A.S.', '6347006588', '400-493-8482');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'SUPERTIENDAS Y DROGUERIAS OLIMPICA S.A', '2529297800', '619-789-4252');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'DRUMMOND LTD', '3317872233', '281-740-0329');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Bavaria S.A.', '7745232708', '595-892-7986');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'PRIMAX COLOMBIA S.A', '5372622490', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'Colombiana de comercio S.A.', '8899538816', '781-494-5572');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'CARBONES DEL CERREJON LIMITED', '0768061237', '801-175-2503');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'CODENSA S.A. E.S.P.', '5113419273', '604-824-7248');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'KOPPS COMMERCIAL S A S', '0447161725', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'C.I. TRAFIGURA PETROLEUM COLOMBIA SAS', '2651726257', NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'MEDIMAS EPS SAS', '8466398813', '736-315-2233');
	INSERT INTO APP_GEST_LOCALES.MBC_EMPRESAS (ID_EMPRESA, NOMBRE, DOCUMENTO, TELEFONO) VALUES (SEQ_MBC_EMPRESAS.NEXTVAL, 'OLEODUCTO CENTRAL SA', '1926471830', NULL);
	
	-- Insertar datos a la tabla "MBC_LOCALES"
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '34932 Crownhardt Court', 479584.8, 296749.59, 1, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '55632 Graedel Crossing', 602809.86, 398565.74, 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '2888 Atwood Center', 391018.85, 166605.89, 3, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '1 Merry Way', 120796.92, 328533.36, 4, 4);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '405 Cottonwood Place', 791073.41, 482772.82, 5, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '8424 Rowland Park', 971774.36, 421613.39, 6, 6);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '0825 Dakota Junction', 219101.39, 373462.86, 7, 7);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '4384 Truax Road', 179203.0, 100785.76, 8, 8);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '00346 Lunder Park', 562836.76, 87926.62, 9, 9);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '61157 Village Way', 174561.18, 40684.02, 10, 10);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '19115 Magdeline Court', 636744.25, 203385.2, 1, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '22757 Eagle Crest Point', 695965.49, 168458.52, 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '5033 Dottie Point', 577923.56, 85516.41, 13, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '5563 Larry Point', 496429.56, 105850.76, 4, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, 'Carrera 72 # 15-18', 500000.00, 50000.00, 2, 17);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '1208 Scoville Hill', 414150.69, 373647.8, 1, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '64387 Hooker Crossing', 524369.39, 173805.8, 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '7 Blaine Court', 557241.0, 349533.33, 3, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '12 Lakeland Avenue', 817119.33, 63770.86, 4, 4);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, 'Calle 17 # 71-45', 250000.00, 25000.00, 1, 17);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '50362 Londonderry Trail', 134368.34, 103022.47, 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '8943 Ronald Regan Lane', 972745.07, 213443.44, 3, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '7 Claremont Alley', 360670.46, 465663.15, 1, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '7245 Commercial Plaza', 602797.23, 270247.55, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_LOCALES (ID_LOCAL, DIRECCION, CUOTA_ARRIENDO, CUOTA_ADMINISTRACION, ID_CIUDAD_LOCAL, ID_EMPRESA) VALUES (SEQ_MBC_LOCALES.NEXTVAL, '1 Harbort Center', 444426.13, 252676.68, 1, 1);
	
	-- Insertar datos a la tabla "MBC_USUARIOS"
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Marlon', 'Pérez', 'marlonp97@hotmail.com', '12345', '548-784-8261', 1, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Administrador', 'Prueba', 'admin@gmail.com', 'admin', '454-588-3362', 1, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Cliente', 'Prueba', 'cliente@gmail.com', 'cliente', '260-191-6824', 2, 17);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Samuele', 'Dugood', 'sdugood3@quantcast.com', 'IaId1nUGyG', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Armin', 'Forsard', 'aforsard4@dot.gov', 'GZqTVY', '431-157-2381', 2, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Sidnee', 'Sanders', 'ssanders5@wunderground.com', 'v2JuFR', '843-338-9259', 2, 4);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Lucio', 'O''Griffin', 'logriffin6@opera.com', 'bCzuxUafCX', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Leighton', 'Custy', 'lcusty7@pinterest.com', 'Gqa2Pn3', '245-181-5743', 2, 6);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Terrence', 'Deason', 'tdeason8@irs.gov', 'Rx72bA', '407-245-4090', 2, 7);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Gerri', 'Haysom', 'ghaysom9@cnn.com', 'HVeH62Pcqg', '373-548-5973', 2, 8);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Pip', 'Darrington', 'pdarringtona@4shared.com', 'OBa1CI', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Hugibert', 'Giorgeschi', 'hgiorgeschib@archive.org', 'jtLsAynkK2V', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Lief', 'Matthaus', 'lmatthausc@prweb.com', 'kjlPqCC6M9Qr', '522-590-2649', 2, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Bren', 'Caso', 'bcasod@elpais.com', '2aaWBF2', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Natale', 'McNaught', 'nmcnaughte@apache.org', 'QP87QqpsB6Cu', '612-284-0409', 2, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Decca', 'Ransbury', 'dransburyf@myspace.com', 'qfWRxyF', '545-498-9432', 2, 4);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Berk', 'Druhan', 'bdruhang@cdc.gov', 'oOadjL0FqsrG', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Currey', 'Giacovetti', 'cgiacovettih@cmu.edu', 'uAWCUBNTG', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Lockwood', 'Volet', 'lvoleti@wix.com', '1Wz6OF9iD', '762-447-3668', 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Gregoor', 'Goldstone', 'ggoldstonej@ucoz.com', 'W57vTn78a6ma', NULL, 2, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Barnabas', 'Adamson', 'badamsonk@ehow.com', 'y6EEPit', '781-897-7244', 2, 4);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Clayton', 'Vergo', 'cvergol@dailymotion.com', 'tTIfUsJqro', '573-891-1959', 2, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Martie', 'Pailin', 'mpailinm@stumbleupon.com', 'DaCfMk9mMf', '715-244-0831', 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Wilden', 'Daveley', 'wdaveleyn@smh.com.au', 'THmowCPrcS', '756-823-0106', 2, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, CORREO, CLAVE, TELEFONO, ID_ROL_USUARIO, ID_EMPRESA) VALUES (SEQ_MBC_USUARIOS.NEXTVAL, 'Rurik', 'Tertre', 'rtertreo@walmart.com', 'VgZIOTX4zrT', '561-136-2585', 2, 15);
	
    -- Insertar datos a la tabla "MBC_PAGOS"
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'pretium quis lectus suspendisse potenti', 822167.08, TO_DATE('2022-01-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 1, 1, 1, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'hac habitasse platea dictumst aliquam', 816988.21, TO_DATE('2022-05-31', 'yyyy-mm-dd'), 'Et.mpeg', 466189.61, TO_DATE('2022-06-19', 'yyyy-mm-dd'), 2, 2, 2, 2, 19);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'aenean lectus pellentesque', 497807.68, TO_DATE('2022-11-30', 'yyyy-mm-dd'), NULL, NULL, NULL, 3, 1, 3, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'suscipit ligula in', 239435.92, TO_DATE('2022-03-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 1, 1, 4, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'molestie lorem quisque ut', 186778.91, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 2, 1, 5, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'erat vestibulum sed magna', 363002.1, TO_DATE('2022-11-30', 'yyyy-mm-dd'), 'Dictumst.avi', 248890.99, TO_DATE('2022-12-12', 'yyyy-mm-dd'), 3, 2, 6, 6, 8);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'sed augue aliquam', 882939.75, TO_DATE('2022-08-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 1, 1, 7, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'morbi porttitor lorem', 393978.3, TO_DATE('2022-01-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 2, 1, 8, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'pretium quis lectus suspendisse', 442516.01, TO_DATE('2022-08-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 3, 1, 1, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'luctus tincidunt NULLa mollis molestie', 991151.46, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 1, 1, 2, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Arriendo enero/2022', 500000.00, TO_DATE('2022-01-31', 'yyyy-mm-dd'), 'Factura.png', 500000.00, TO_DATE('2022-01-15', 'yyyy-mm-dd'), 1, 3, 15, 17, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Arriendo enero/2022', 250000.00, TO_DATE('2022-01-31', 'yyyy-mm-dd'), 'Factura.png', 250000.00, TO_DATE('2022-01-16', 'yyyy-mm-dd'), 1, 3, 20, 17, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Administración enero/2022', 50000.00, TO_DATE('2022-01-31', 'yyyy-mm-dd'), 'Factura.png', 50000.00, TO_DATE('2022-01-14', 'yyyy-mm-dd'), 2, 3, 15, 17, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Administración enero/2022', 25000.00, TO_DATE('2022-01-31', 'yyyy-mm-dd'), 'Factura.png', 25000.00, TO_DATE('2022-01-13', 'yyyy-mm-dd'), 2, 3, 20, 17, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Pintura local enero/2022', 1000000.00, TO_DATE('2022-01-31', 'yyyy-mm-dd'), 'Factura.png', 1000000.00, TO_DATE('2022-01-20', 'yyyy-mm-dd'), 3, 3, 15, 17, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Arriendo febrero/2022', 500000.00, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 1, 1, 15, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Arriendo febrero/2022', 250000.00, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 1, 1, 20, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Administración febrero/2022', 50000.00, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 2, 1, 15, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Administración febrero/2022', 25000.00, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 2, 1, 20, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'Pintura local febrero/2022', 1000000.00, TO_DATE('2022-02-28', 'yyyy-mm-dd'), NULL, NULL, NULL, 3, 1, 15, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'consectetuer adipiscing elit proin', 259847.6, TO_DATE('2022-12-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 3, 1, 2, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'maecenas pulvinar lobortis est phasellus', 561952.04, TO_DATE('2022-09-30', 'yyyy-mm-dd'), 'FringillaRhoncus.avi', 401735.41, TO_DATE('2022-04-19', 'yyyy-mm-dd'), 1, 2, 3, 3, 5);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'NULLa dapibus dolor', 863656.2, TO_DATE('2022-12-31', 'yyyy-mm-dd'), NULL, NULL, NULL, 2, 1, 1, NULL, NULL);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'id turpis integer aliquet massa', 781750.95, TO_DATE('2022-05-31', 'yyyy-mm-dd'), 'EnimLoremIpsum.avi', 774151.02, TO_DATE('2022-06-17', 'yyyy-mm-dd'), 3, 2, 2, 2, 23);
	INSERT INTO APP_GEST_LOCALES.MBC_PAGOS (ID_PAGO, DESCRIPCION, PRECIO, FECHA_VENCIMIENTO, SOPORTE, VALOR_PAGADO, FECHA_PAGO, ID_TIPO_PAGO, ID_ESTADO_PAGO, ID_LOCAL, ID_EMPRESA, ID_USUARIO) VALUES (SEQ_MBC_PAGOS.NEXTVAL, 'arcu sed augue', 984225.3, TO_DATE('2022-12-31', 'yyyy-mm-dd'), 'VitaeNislAenean.doc', 564184.64, TO_DATE('2022-07-06', 'yyyy-mm-dd'), 1, 3, 1, 1, 13);
    
	-- Insertar datos a la tabla "MBC_CASOS"
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', NULL, 1, 1, 1);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'phasellus sit amet erat NULLa', 'Lectus.txt', 2, 2, 2);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis', 'UltricesVel.mov', 13, 1, 3);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'NULLa suspendisse potenti cras in purus eu magna vulputate', 'VestibulumVestibulumAnte.jpeg', 4, 2, 4);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'convallis eget eleifend luctus ultricies eu nibh', 'PretiumNislUt.xls', 5, 1, 5);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'phasellus in felis donec semper sapien a libero nam', 'NonummyMaecenas.tiff', 6, 2, 6);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'id ornare imperdiet sapien urna pretium nisl ut volutpat', 'Eu.ppt', 7, 1, 7);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'ut suscipit a feugiat et eros vestibulum ac est', 'CongueEtiam.ppt', 8, 2, 8);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'sit amet sapien dignissim vestibulum vestibulum', NULL, 9, 1, 9);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 'VelitEuEst.xls', 10, 2, 10);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 'NislNuncRhoncus.avi', 1, 1, 21);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', 'NisiVenenatis.avi', 2, 2, 22);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'nisi at nibh in hac habitasse platea', NULL, 13, 1, 23);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'eget tincidunt eget tempus vel', 'MagnaVestibulumAliquet.ppt', 1, 2, 24);
	INSERT INTO APP_GEST_LOCALES.MBC_CASOS (ID_CASO, DESCRIPCION, SOPORTE, ID_USUARIO, ID_ESTADO_CASO, ID_PAGO) VALUES (SEQ_MBC_CASOS.NEXTVAL, 'volutpat quam pede lobortis ligula sit amet eleifend', 'Habitasse.avi', 2, 1, 25);
	
	COMMIT;

EXCEPTION

	WHEN OTHERS THEN
    
		ROLLBACK;
		raise_application_error(-20000, SQLCODE ||'=>'|| SQLERRM, TRUE);

END;